version: "3.2"

services:
  permission-service:
    build:
      context: .
      dockerfile: bin/authority-service/docker/authority-service.Dockerfile

  validator-alice:
    image: bright/substrate-raft-setup
    ports:
      - "9944:9944"
      - "9615:9615"
    command:
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000001"
      - "--base-path"
      - "/tmp/alice-1"
      - "--chain=local"
      - "--port"
      - "30333"
      - "--validator"
      - "--alice"
      - "--remote-authority=http://permission-service:8000"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
