version: "3.2"

services:
  permission-service:
    build:
      context: .
      dockerfile: bin/authority-service/docker/authority-service.Dockerfile

  validator-alice:
    image: bright/substrate-raft-setup
    ports:
      - "9944:9944"
      - "9615:9615"
    command:
      - "--dev"
      - "--remote-authority=http://permission-service:8000"
