[package]
name = "authority-service"
version = "0.1.0"
description = "Authority service"
edition = "2021"

[[bin]]
name = "authority-service"

[workspace]

[dependencies]
rocket = "0.5.0-rc.2"
serde = "1.0"
serde_json = "1.0"